version: '3.1'

services:

  db:
    container_name: reddit-scraper-db
    image: postgres
    restart: always

    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: toor
    volumes:
      - ./dbData:/var/lib/postgresql/data